2018-05-03 23:56:55,585 INFO: Microblog startup [in /Users/fimasik/Projects/python-flask_tutor/microblog/app/__init__.py:50]
2018-05-03 23:59:49,224 ERROR: Exception on /edit_profile [POST] [in /Users/fimasik/.virtualenvs/python-flask_tutor/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/fimasik/.virtualenvs/python-flask_tutor/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/fimasik/.virtualenvs/python-flask_tutor/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/fimasik/.virtualenvs/python-flask_tutor/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/fimasik/.virtualenvs/python-flask_tutor/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/fimasik/.virtualenvs/python-flask_tutor/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/fimasik/.virtualenvs/python-flask_tutor/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/fimasik/.virtualenvs/python-flask_tutor/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/fimasik/.virtualenvs/python-flask_tutor/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/fimasik/.virtualenvs/python-flask_tutor/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/fimasik/Projects/python-flask_tutor/microblog/app/routes.py", line 102, in edit_profile
    db.session.commit()
  File "/Users/fimasik/.virtualenvs/python-flask_tutor/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/fimasik/.virtualenvs/python-flask_tutor/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/Users/fimasik/.virtualenvs/python-flask_tutor/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/Users/fimasik/.virtualenvs/python-flask_tutor/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/Users/fimasik/.virtualenvs/python-flask_tutor/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/Users/fimasik/.virtualenvs/python-flask_tutor/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/fimasik/.virtualenvs/python-flask_tutor/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/fimasik/.virtualenvs/python-flask_tutor/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/Users/fimasik/.virtualenvs/python-flask_tutor/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2344, in _flush
    flush_context.execute()
  File "/Users/fimasik/.virtualenvs/python-flask_tutor/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/Users/fimasik/.virtualenvs/python-flask_tutor/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
    uow
  File "/Users/fimasik/.virtualenvs/python-flask_tutor/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
    mapper, table, update)
  File "/Users/fimasik/.virtualenvs/python-flask_tutor/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 768, in _emit_update_statements
    execute(statement, multiparams)
  File "/Users/fimasik/.virtualenvs/python-flask_tutor/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/Users/fimasik/.virtualenvs/python-flask_tutor/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/fimasik/.virtualenvs/python-flask_tutor/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/fimasik/.virtualenvs/python-flask_tutor/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/Users/fimasik/.virtualenvs/python-flask_tutor/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/Users/fimasik/.virtualenvs/python-flask_tutor/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/fimasik/.virtualenvs/python-flask_tutor/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/Users/fimasik/.virtualenvs/python-flask_tutor/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/fimasik/.virtualenvs/python-flask_tutor/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username [SQL: 'UPDATE user SET username=?, about_me=? WHERE user.id = ?'] [parameters: ('susan', 'hello', 2)] (Background on this error at: http://sqlalche.me/e/gkpj)
2018-05-04 00:00:29,639 INFO: Microblog startup [in /Users/fimasik/Projects/python-flask_tutor/microblog/app/__init__.py:50]
2018-05-04 00:07:26,071 INFO: Microblog startup [in /Users/fimasik/Projects/python-flask_tutor/microblog/app/__init__.py:50]
2018-05-04 00:24:48,849 INFO: Microblog startup [in /Users/fimasik/Projects/python-flask_tutor/microblog/app/__init__.py:50]
2018-05-04 00:24:57,810 INFO: Microblog startup [in /Users/fimasik/Projects/python-flask_tutor/microblog/app/__init__.py:50]
2018-05-04 00:50:01,087 INFO: Microblog startup [in /Users/fimasik/Projects/python-flask_tutor/microblog/app/__init__.py:50]
2018-05-04 01:00:31,890 INFO: Microblog startup [in /Users/fimasik/Projects/python-flask_tutor/microblog/app/__init__.py:50]
2018-05-04 01:07:59,686 INFO: Microblog startup [in /Users/fimasik/Projects/python-flask_tutor/microblog/app/__init__.py:50]
2018-05-04 01:11:30,727 INFO: Microblog startup [in /Users/fimasik/Projects/python-flask_tutor/microblog/app/__init__.py:50]
2018-05-04 01:12:14,963 INFO: Microblog startup [in /Users/fimasik/Projects/python-flask_tutor/microblog/app/__init__.py:50]
2018-05-04 01:14:06,094 INFO: Microblog startup [in /Users/fimasik/Projects/python-flask_tutor/microblog/app/__init__.py:50]
2018-05-04 01:20:25,301 INFO: Microblog startup [in /Users/fimasik/Projects/python-flask_tutor/microblog/app/__init__.py:50]
2018-05-04 01:30:47,698 INFO: Microblog startup [in /Users/fimasik/Projects/python-flask_tutor/microblog/app/__init__.py:50]
2018-05-04 01:34:22,616 INFO: Microblog startup [in /Users/fimasik/Projects/python-flask_tutor/microblog/app/__init__.py:50]
2018-05-04 10:23:47,847 INFO: Microblog startup [in /Users/fimasik/Projects/python-flask_tutor/microblog/app/__init__.py:53]
